name: linting, testing, building
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]
        permissions:
            contents: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: npm ci
            - name: build production project
              run: npm run build:prod
            - name: linting typescript
              run: npm run lint:ts
            - name: linting css
              run: npm run lint:scss
            - name: unit testing
              run: npm run test:unit
            - name: build storybook
              run: npm run build:storybook
            - name: screenshot testing
              run: npm run test:ui:ci
            - name: screenshots difference
            
              run: /
                date > generated.txt
                git config user.name github-actions
                git config user.email github-actions@github.com
                git add .
                git checkout -b screenshots
                git commit -m "failure screensshots"
                git push -f origin screenshots

